---
restylers:
  - brittany:
      include:
        - "backend/**/*.hs"
        - "!backend/aws-xray-client/tests/Network/AWS/XRayClient/SegmentSpec.hs"
        - "!backend/fancy-api/library/Application.hs"
        - "!backend/fancy-api/library/Foundation.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/Ela/AdaptiveSkill.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/Ela/Articles.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/Ela/WordStudy.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/Math.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/School.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/School/Reports/MathAdaptiveGradeLevel.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Dal/Teacher.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/ActivityFeed.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/AdGuides.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/DistrictAssessment/Answers.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Ela/AssessmentReport.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Math/Adaptive/GameSessions.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Math/Assessment/Answer.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Math/Standard/GameSessions.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Math/Worksheet.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/PasswordsResets.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/QuoteRequestForm.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Referrals.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Schools.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Student/DetailedAnalysis.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Math/Adaptive/Model/Answer.hs"
        - "!backend/fancy-api/library/FrontRow/Api/RollUps.hs"
        - "!backend/fancy-api/library/FrontRow/Api/SchoolAdmin/Emails.hs"
        - "!backend/fancy-api/library/Settings.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Course/Ela/Article/DomainSummariesSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Dal/Math/AssignmentSessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/ActivityFeedSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/BadgesSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/ColleagueSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Console/AgentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/AssignmentCountsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/Ela/AdaptiveSkills/Reports/Deprecated/SkillGroupsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/Ela/AdaptiveSkills/Reports/SkillGroupsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/Reports/Math/Targeted/AssignmentsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/StudentActivityStatusSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/Subject/Product/SessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/SubjectsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Course/UnmanagedSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DemoDistrictsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DistrictAssessment/Report/CourseStudentOverviewSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DistrictAssessment/Report/GradesSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DistrictAssessment/Report/SchoolsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DistrictAssessmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/District/RostersSisIdSyncSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DistrictSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/DistrictsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/District/RostersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/District/Student/PlacementSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AdaptiveSkill/AssignmentAnswersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AdaptiveSkill/Courses/SessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AdaptiveSkill/DomainSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AdaptiveSkill/PassageSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AdaptiveSkill/SystemDomains/SummarySpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/Articles/ArticlesSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AssignmentAnswerSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/AssignmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/CourseAssignmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/ClassActivitySpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/Progress/StudentsElaProgressSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/ReportCardSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/SightWords/LevelSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/SightWords/SessionSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/SightWords/WordSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/TargetedSkill/AssignmentAnswersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/TargetedSkill/AssignmentSessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/TargetedSkill/AssignmentsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/TargetedSkill/PassageSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/WordStudy/AssignmentsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/WordStudy/LevelsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Ela/WordStudy/SessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Adaptive/AssignmentAnswerSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Adaptive/GameSessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Assessment/AnswerSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Assessment/GrowthStatsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/AssignmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Progress/StudentsMathProgressSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/ReportCardSummarySpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Standard/GameSessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Math/Standard/TargetedAssignmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/PremiumLicensesSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/ReferralsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolAdmin/AssessorsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolAdmin/DistrictAssessmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolAdmin/PermissionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolAdmin/RostersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolLeadSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/School/LicensesSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/School/Math/Assessment/AssignmentSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/School/ReportsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/SchoolsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Student/GoalsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Student/IdpOverlaySpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Student/MathDomainRecommendationsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Student/PatchSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Student/StudentShareSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Subject/Product/Sessions/AnswersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Subject/Product/Sessions/AttemptsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Subject/Product/SessionsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Teacher/SessionSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/TeacherSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Units/Science/AssignmentAnswersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/Handlers/Units/SocialStudies/AssignmentAnswersSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Api/RollUpsSpec.hs"
        - "!backend/fancy-api/tests/FrontRow/Test/Article/ResumableSessions.hs"
        - "!backend/fancy-api/tests/FrontRow/Test/Subject/Product/Sessions.hs"
        - "!backend/fancy-api/tests/TestAuth.hs"
        - "!backend/entities/library/FrontRow/Entities/Math/AssessmentAnswer.hs"
        - "!backend/entities/library/FrontRow/Entities/StudentMathDomainRecommendation.hs"
        - "!backend/entities/library/FrontRow/Math/Logic/Question.hs"
        - "!backend/entities/library/FrontRow/Math/Question.hs"
        - "!backend/entities/library/FrontRow/Model.hs"
        - "!backend/entities/library/FrontRow/Test/Factories.hs"
        - "!backend/entities/library/FrontRow/Test/Fixtures/Standards.hs"
        - "!backend/core/tests/FrontRow/Core/Math/AnswerSpec.hs"
        - "!backend/jobs/library/FrontRow/Jobs/SendDailyTeacherEmail/CourseStat.hs"
        - "!backend/jobs/library/FrontRow/Jobs/SendWeeklyTeacherEmail/Legacy/Reports/Math/StudentData.hs"
        - "!backend/jobs/tests/FrontRow/Jobs/RecordLicenseUtilization/NotificationEmailSpec.hs"
        - "!backend/jobs/tests/FrontRow/Jobs/SyncCleverGoalsSpec.hs"
        - "!backend/core/library/FrontRow/Json.hs"
        - "!backend/core/library/FrontRow/Persist.hs"
        - "!backend/core/tests/FrontRow/JsonSpec.hs"
        - "!backend/roster-management/tests/FrontRow/RosterManagement/SisIdSync/LogicSpec.hs"
        - "!backend/text-assets/executables/text-assets.hs"
        - "!backend/text-assets/library/FrontRow/TextAssets/Math/Standards.hs"
  - shfmt:
      arguments:
        - -i
        - "2"
        - -ci
  - stylish-haskell:
      include:
        - "**/*.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Auth/Google.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Ela/Assignment.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Handlers/Units/Assignments.hs"
        - "!backend/fancy-api/library/FrontRow/Api/Pagination.hs"
        - "!backend/fr-slack-api/library/FrontRow/Fr/SlackApi.hs"

comments: false

labels:
  - restyled
  - pullassigner-ignore
