---
name: asana

dependencies:
  - base
  - monad-logger

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - aeson-casing
    - http-conduit
    - iso8601-time
    - load-env
    - optparse-applicative
    - text
    - time
    - transformers
    - unliftio

executables:
  bug-reproduction:
    main: Main.hs
    source-dirs: bug-reproduction
    dependencies:
      - asana
      - semigroups
      - text
      - time
  close-iteration:
    main: Main.hs
    source-dirs: close-iteration
    dependencies:
      - asana
      - unliftio
  start-iteration:
    main: Main.hs
    source-dirs: start-iteration
    dependencies:
      - asana
      - unliftio
  debt-evaluation:
    main: Main.hs
    source-dirs: debt-evaluation
    dependencies:
      - asana
      - text
      - unliftio
