name: asana-cli

dependencies:
  - base

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - Blammo
    - asana
    - bytestring
    - envparse
    - lens
    - load-env
    - mtl
    - optparse-applicative
    - scientific
    - text
    - time
    - unliftio
    - unliftio-core

executables:
  bug-reproduction:
    main: Main.hs
    source-dirs: bug-reproduction
    dependencies:
      - asana
      - asana-cli
      - semigroups
      - time
  close-iteration:
    main: Main.hs
    source-dirs: close-iteration
    dependencies:
      - asana
      - asana-cli
      - semigroups
      - text
      - unliftio
  start-iteration:
    main: Main.hs
    source-dirs: start-iteration
    dependencies:
      - asana
      - asana-cli
      - text
      - transformers
      - unliftio
  debt-evaluation:
    main: Main.hs
    source-dirs: debt-evaluation
    dependencies:
      - asana
      - asana-cli
      - unliftio
  cycle-time:
    main: Main.hs
    source-dirs: cycle-time
    dependencies:
      - asana
      - asana-cli
      - bytestring
      - cassava
      - containers
      - statistics
      - temporary
      - text
      - time
      - unliftio
      - vector
  educator-zombie-tasks:
    main: Main.hs
    source-dirs: educator-zombie-tasks
    dependencies:
      - aeson
      - aeson-casing
      - asana
      - asana-cli
      - http-conduit
      - scientific
      - shakespeare
      - statistics
      - text
      - time
      - unliftio
      - unordered-containers
      - vector
  update-task:
    main: Main.hs
    source-dirs: update-task
    dependencies:
      - asana
      - asana-cli
      - optparse-applicative
      - text
  planning-poker:
    main: Main.hs
    source-dirs: planning-poker
    dependencies:
      - asana
      - asana-cli
      - bytestring
      - cassava
      - text
      - unliftio
      - unordered-containers
