---
name: asana

dependencies:
  - base

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - aeson-casing
    - http-conduit
    - load-env
    - optparse-applicative
    - rio
    - scientific
    - safe

executables:
  bug-reproduction:
    main: Main.hs
    source-dirs: bug-reproduction
    dependencies:
      - asana
      - rio
      - semigroups
  close-iteration:
    main: Main.hs
    source-dirs: close-iteration
    dependencies:
      - asana
      - rio
      - semigroups
  start-iteration:
    main: Main.hs
    source-dirs: start-iteration
    dependencies:
      - asana
      - rio
      - transformers
  debt-evaluation:
    main: Main.hs
    source-dirs: debt-evaluation
    dependencies:
      - asana
      - rio
  cycle-time:
    main: Main.hs
    source-dirs: cycle-time
    dependencies:
      - asana
      - cassava
      - containers
      - rio
      - statistics
      - temporary
      - vector
  update-task:
    main: Main.hs
    source-dirs: update-task
    dependencies:
      - asana
      - optparse-applicative
      - rio
      - text
  planning-poker:
    main: Main.hs
    source-dirs: planning-poker
    dependencies:
      - asana
      - rio
      - text
      - cassava
