resolver: lts-14.20
packages:
- .
# NB. -fignore-optim-changes can get in the way of profiling projects. To
# build for profiling, consider using a separate .stack-work directory or
# reversing the flag using `fno-ignore-optim-changes`.
ghc-options:
  "$locals":
    -ddump-to-file
    -ddump-hi
    -fhide-source-paths
    -Weverything
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-import-lists
    -Wno-implicit-prelude
    -fignore-optim-changes
