resolver: lts-19.1
packages:
- .
# NB. -fignore-optim-changes can get in the way of profiling projects. To
# build for profiling, consider using a separate .stack-work directory or
# reversing the flag using `fno-ignore-optim-changes`.
ghc-options:
  "$locals": -fwrite-ide-info
    -fhide-source-paths
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-monadfail-instances
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module
    -fignore-optim-changes
